### ISSUE TITLE
serde support?

### ISSUE THREAD

**Issue by cbeck88** [Amanieu/hashmap_core#9]
Was interested in this crate because I need a hashmap that is compatible with `no_std` and compatible with `serde`.

I tried `hashbrown` hashmap, but I am getting strange panics reported -- I'm not sure if it's due to hashbrown, I wanted to try a different implementation.

**Comment by Amanieu** [comment]
This crate is deprecated and not really maintained any more. I suggest that you use `hashbrown` instead.

**Comment by cbeck88** [comment]
We tried using `hashbrown` but we got assertion failures at this line in debug builds:

```
thread panicked at 'Box<Any>', /root/cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.1.8/src/raw/sse2.rs:51:9
```

https://github.com/Amanieu/hashbrown/blob/master/src/raw/sse2.rs#L51

```
    /// Loads a group of bytes starting at the given address, which must be
    /// aligned to `mem::align_of::<Group>()`.
    #[inline]
    pub unsafe fn load_aligned(ptr: *const u8) -> Group {
        debug_assert_eq!(ptr as usize & (mem::align_of::<Group>() - 1), 0);
        Group(x86::_mm_load_si128(ptr as *const _))
    }
```

I can try to provide a reduced test case that repros this, but I can't prioritize that above my current work right now, sorry.

For now we have settled on bringing rust stdlib hashmap sources in tree and patching the part where they use OS rng to use `RDRAND` instruction anyways -- at that point they compile as `no_std`. Since we are only targetting x86 (but we target intel SGX enclave as well which is why we need `no_std`), that's good enough for us. 

Thanks for your hard work providing so many nicely designed rust libraries to the open source community!

**Comment by Amanieu** [comment]
This assert happens because your allocator isn't respecting the alignment requirements. `hashbrown` allocates tables with 16-byte alignment, which is required for SSE instructions.

**Comment by cbeck88** [comment]
Thanks for the tip, will seek to confirm in our project

Edit: That was indeed the case, thanks
